[phases.setup]
nixPkgs = ["nodejs", "python3"]

[phases.install]
cmds = [
  "npm install",
  "python3 -m ensurepip",
  "python3 -m pip install -r app/python/requirements.txt"
]

[phases.build]
cmds = ["npm run build"]

[phases.start]
cmd = "npm run start"
