[phases.setup]
nixPkgs = ["nodejs", "python311Full"]

[phases.install]
cmds = [
  "npm install",
  "python3 -m pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = ["npm run build"]

[phases.start]
cmd = "npm run start"
