[phases.setup]
nixPkgs = ["nodejs", "python3", "pip"]

[phases.install]
cmds = [
  "npm install",
  "pip install -r app/python/requirements.txt"
]

[phases.build]
cmds = ["npm run build"]

[phases.start]
cmd = "npm run start"
